#!/usr/bin/env python3
"""Generate the L2 brief index (vault/02 Briefs/README.md) from brief frontmatter.

Reads every L2 brief under ``vault/02 Briefs/`` (skipping README.md itself), pulls the
``title`` / ``theme`` / ``week`` / ``updated`` / ``sources`` from each brief's frontmatter,
and renders a single index table — "all briefs + last-updated", the F2 brief-index the KR
asks for. It also lists the themes that are surfaced as L1 but whose L2 brief is being held
(read from ``sources/registry.json`` themes vs. the briefs actually on disk), so the index is
honest about coverage.

Pure stdlib + reuse of ``synthesis.lint.split_frontmatter`` (the same parser the lint uses,
so the index can never disagree with what the lint validated). Idempotent: running it again
with no brief changes rewrites the same file.

Usage:
    python scripts/build_brief_index.py            # write vault/02 Briefs/README.md
    python scripts/build_brief_index.py --check     # exit 1 if README.md is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from synthesis.lint import split_frontmatter  # noqa: E402

_BRIEFS_DIR = _REPO_ROOT / "vault" / "02 Briefs"
_REGISTRY = _REPO_ROOT / "sources" / "registry.json"
_INDEX = _BRIEFS_DIR / "README.md"


def _briefs() -> list[dict[str, str]]:
    out: list[dict[str, str]] = []
    for path in sorted(_BRIEFS_DIR.glob("*.md")):
        if path.name.lower() == "readme.md":
            continue
        fm, _ = split_frontmatter(path.read_text(encoding="utf-8"))
        fm = fm or {}
        out.append(
            {
                "file": path.name,
                "title": fm.get("title", path.stem),
                "theme": fm.get("theme", ""),
                "week": fm.get("week", ""),
                "updated": fm.get("updated", ""),
                "sources": fm.get("sources", ""),
            }
        )
    return out


def _held_themes(briefed: set[str]) -> list[tuple[str, str, str]]:
    """Themes declared in the registry that have no brief on disk yet (surfaced, held).

    Returns (title, slug, hold_reason) so the index can explain *why* a surfaced theme has
    no L2 brief yet.
    """
    data = json.loads(_REGISTRY.read_text(encoding="utf-8"))
    themes: dict[str, dict[str, str]] = data.get("themes", {})
    surfaced_themes = {
        s.get("theme", "") for s in data.get("sources", []) if s.get("surfaced") and s.get("theme")
    }
    held: list[tuple[str, str, str]] = []
    for slug, meta in themes.items():
        if slug in surfaced_themes and slug not in briefed:
            held.append((meta.get("title", slug), slug, meta.get("hold_reason", "")))
    return sorted(held)


def render() -> str:
    briefs = _briefs()
    briefed_themes = {b["theme"] for b in briefs if b["theme"]}
    lines = [
        "# azimuth Briefs — Index",
        "",
        "Auto-generated by `scripts/build_brief_index.py` from each brief's frontmatter — do",
        "not edit by hand. One L2 brief per editorially-clean theme; each evolves in place",
        "weekly (see its `## Changelog`). All content is CC-BY-4.0; see `../../CREDITS.md`.",
        "",
        "| Brief | Theme | Week | Last updated | L1 sources |",
        "| --- | --- | --- | --- | --- |",
    ]
    for b in briefs:
        link = f"[{b['title']}](<{b['file']}>)"
        lines.append(f"| {link} | {b['theme']} | {b['week']} | {b['updated']} | {b['sources']} |")

    held = _held_themes(briefed_themes)
    if held:
        lines += [
            "",
            "## Surfaced themes with a held brief",
            "",
            "These themes are ingested as L1 (they pass the source-guardrail) but their L2",
            "brief is held for an editorial reason — see `sources/registry.json` and the",
            "project note. They will be briefed once the held condition clears.",
            "",
        ]
        for title, slug, reason in held:
            tail = f" {reason}" if reason else ""
            lines.append(f"- **{title}** (`{slug}`) — L1 ingested, L2 brief held.{tail}")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="build the azimuth L2 brief index")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if the index is stale (CI guard)"
    )
    args = parser.parse_args()

    new = render()
    if args.check:
        current = _INDEX.read_text(encoding="utf-8") if _INDEX.exists() else ""
        if current != new:
            print("brief-index: STALE — run `python scripts/build_brief_index.py` and commit.")
            return 1
        print("brief-index: up to date.")
        return 0

    _INDEX.write_text(new, encoding="utf-8")
    print(f"brief-index: wrote {_INDEX.relative_to(_REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
