#!/usr/bin/env python3
"""Generate the OKF-reserved ``index.md`` directory listing at every ``vault/`` level.

OKF v0.1 §6 reserves the filename ``index.md`` for a per-directory listing that gives a
consumer agent *progressive disclosure*: each folder's ``index.md`` links only to its own
immediate children — sub-folders link down to their child ``index.md`` (drill in), content
files link to the file itself. Per the spec the reserved ``index.md`` carries **no
frontmatter** (it is navigation, not a concept note). The human-facing ``README.md`` is
kept as the landing page and listed alongside the content files; the two coexist (this is
the "keep README as the human landing page" option from the OKF Tier-1 plan, not "fold").

Reuses the ``synthesis.lint.split_frontmatter`` parser (the same one the brief index and the
synthesis lint use) so a file's displayed title can never disagree with what the lint reads.
Pure stdlib otherwise. Idempotent: re-running with no tree change rewrites the same bytes.

Usage:
    python scripts/build_index.py            # (re)write vault/**/index.md
    python scripts/build_index.py --check     # exit 1 if any index.md is stale / has a
                                              # broken link (CI guard)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from synthesis.lint import split_frontmatter  # noqa: E402

_VAULT = _REPO_ROOT / "vault"
_INDEX_NAME = "index.md"


def _title_for(path: Path) -> str:
    """Best display title for a markdown file: frontmatter ``title`` > first ``# H1`` > stem."""
    text = path.read_text(encoding="utf-8")
    fm, body = split_frontmatter(text)
    if fm and fm.get("title"):
        return str(fm["title"])
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("# "):
            return stripped[2:].strip()
    return path.stem


def _child_dirs(folder: Path) -> list[Path]:
    return sorted((p for p in folder.iterdir() if p.is_dir()), key=lambda p: p.name)


def _child_md_files(folder: Path) -> list[Path]:
    return sorted(
        (
            p
            for p in folder.iterdir()
            if p.is_file() and p.suffix == ".md" and p.name != _INDEX_NAME
        ),
        key=lambda p: p.name,
    )


def render(folder: Path) -> str:
    """Render the ``index.md`` body for one directory (no frontmatter — OKF §6)."""
    rel = folder.relative_to(_REPO_ROOT).as_posix()
    title = "vault" if folder == _VAULT else folder.name
    lines = [
        f"# {title} — Index",
        "",
        "OKF v0.1 reserved directory listing (`index.md`, no frontmatter). Auto-generated by",
        "`scripts/build_index.py` — do not edit by hand. The human landing page for this folder",
        f"is `README.md` (if present). Path: `{rel}/`.",
        "",
    ]

    dirs = _child_dirs(folder)
    if dirs:
        lines += ["## Folders", ""]
        for d in dirs:
            # Progressive disclosure: drill into the child's own index.md.
            lines.append(f"- [{d.name}/](<{d.name}/{_INDEX_NAME}>)")
        lines.append("")

    files = _child_md_files(folder)
    if files:
        lines += ["## Files", ""]
        for f in files:
            label = "Human landing page" if f.name.lower() == "readme.md" else _title_for(f)
            lines.append(f"- [{label}](<{f.name}>)")
        lines.append("")

    if not dirs and not files:
        lines += ["_Empty folder._", ""]

    return "\n".join(lines).rstrip("\n") + "\n"


def _all_dirs() -> list[Path]:
    """Every directory under ``vault/`` (inclusive), so each level gets an ``index.md``."""
    out = [_VAULT]
    out += [p for p in _VAULT.rglob("*") if p.is_dir()]
    return sorted(out, key=lambda p: p.as_posix())


def _broken_links(folder: Path, content: str) -> list[str]:
    """Return any link target in ``content`` that does not resolve to a file on disk."""
    broken: list[str] = []
    for line in content.splitlines():
        # links are rendered as [..](<target>) — pull the target between <>.
        start = line.find("](<")
        if start == -1:
            continue
        end = line.find(">)", start)
        if end == -1:
            continue
        target = line[start + 3 : end]
        if not (folder / target).exists():
            broken.append(target)
    return broken


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="build the OKF reserved per-folder index.md")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if any index.md is stale or has a broken link"
    )
    args = parser.parse_args(argv)

    dirs = _all_dirs()

    if args.check:
        stale: list[str] = []
        broken: list[str] = []
        for folder in dirs:
            new = render(folder)
            index = folder / _INDEX_NAME
            current = index.read_text(encoding="utf-8") if index.exists() else ""
            if current != new:
                stale.append(index.relative_to(_REPO_ROOT).as_posix())
            for target in _broken_links(folder, new):
                broken.append(
                    f"{(folder / _INDEX_NAME).relative_to(_REPO_ROOT).as_posix()} -> {target}"
                )
        if stale or broken:
            if stale:
                print("index: STALE — run `python scripts/build_index.py` and commit:")
                for s in stale:
                    print(f"  - {s}")
            if broken:
                print("index: BROKEN LINKS:")
                for b in broken:
                    print(f"  - {b}")
            return 1
        print(f"index: up to date ({len(dirs)} folders, all links resolve).")
        return 0

    for folder in dirs:
        (folder / _INDEX_NAME).write_text(render(folder), encoding="utf-8")
    print(f"index: wrote {len(dirs)} index.md files under vault/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
